// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VisualProgramming.Infrastructure;

#nullable disable

namespace VisualProgramming.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514034420_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VisualProgramming.Domain.Base.BaseNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.ToTable("BaseNodes", (string)null);

                    b.HasDiscriminator<string>("NodeType").HasValue("BaseNode");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("id_element_graf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("in_element_graf_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("out_element_graf_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("source_port_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("target_port_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("id_element_graf");

                    b.HasIndex("in_element_graf_id");

                    b.HasIndex("out_element_graf_id");

                    b.HasIndex("source_port_id");

                    b.HasIndex("target_port_id");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.ElementGraf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsModul")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelLevelOfDepthOperation")
                        .HasColumnType("integer");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("id_element_graf")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("id_node")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("id_element_graf");

                    b.HasIndex("id_node");

                    b.ToTable("ElementGrafs");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Graf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("id_project")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("id_project");

                    b.ToTable("Grafs");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.NodePortConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("id_node")
                        .HasColumnType("uuid");

                    b.Property<Guid>("id_port")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("id_node");

                    b.HasIndex("id_port");

                    b.ToTable("NodePortConnections");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("TypePort")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Modul", b =>
                {
                    b.HasBaseType("VisualProgramming.Domain.Base.BaseNode");

                    b.Property<Guid>("id_operation")
                        .HasColumnType("uuid");

                    b.HasIndex("id_operation");

                    b.HasDiscriminator().HasValue("Modul");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Node", b =>
                {
                    b.HasBaseType("VisualProgramming.Domain.Base.BaseNode");

                    b.Property<int>("TypeOperation")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Node");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Connection", b =>
                {
                    b.HasOne("VisualProgramming.Domain.Entites.ElementGraf", null)
                        .WithMany("ElementGrafConnections")
                        .HasForeignKey("id_element_graf");

                    b.HasOne("VisualProgramming.Domain.Entites.ElementGraf", "InElementGraf")
                        .WithMany()
                        .HasForeignKey("in_element_graf_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisualProgramming.Domain.Entites.ElementGraf", "OutElementGraf")
                        .WithMany()
                        .HasForeignKey("out_element_graf_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisualProgramming.Domain.Entites.Port", "SourcePort")
                        .WithMany()
                        .HasForeignKey("source_port_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisualProgramming.Domain.Entites.Port", "TargetPort")
                        .WithMany()
                        .HasForeignKey("target_port_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InElementGraf");

                    b.Navigation("OutElementGraf");

                    b.Navigation("SourcePort");

                    b.Navigation("TargetPort");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.ElementGraf", b =>
                {
                    b.HasOne("VisualProgramming.Domain.Entites.Graf", "ParentGraf")
                        .WithMany("elementsGraf")
                        .HasForeignKey("id_element_graf");

                    b.HasOne("VisualProgramming.Domain.Base.BaseNode", "Node")
                        .WithMany()
                        .HasForeignKey("id_node");

                    b.Navigation("Node");

                    b.Navigation("ParentGraf");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Graf", b =>
                {
                    b.HasOne("VisualProgramming.Domain.Entites.Project", "Project")
                        .WithMany("_grafs")
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.NodePortConnection", b =>
                {
                    b.HasOne("VisualProgramming.Domain.Base.BaseNode", "Node")
                        .WithMany("nodePortConnections")
                        .HasForeignKey("id_node")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisualProgramming.Domain.Entites.Port", "Port")
                        .WithMany("nodePortConnections")
                        .HasForeignKey("id_port")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Port", b =>
                {
                    b.HasOne("VisualProgramming.Domain.Base.BaseNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Modul", b =>
                {
                    b.HasOne("VisualProgramming.Domain.Entites.Graf", "GrafOperation")
                        .WithMany()
                        .HasForeignKey("id_operation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrafOperation");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Base.BaseNode", b =>
                {
                    b.Navigation("nodePortConnections");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.ElementGraf", b =>
                {
                    b.Navigation("ElementGrafConnections");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Graf", b =>
                {
                    b.Navigation("elementsGraf");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Port", b =>
                {
                    b.Navigation("nodePortConnections");
                });

            modelBuilder.Entity("VisualProgramming.Domain.Entites.Project", b =>
                {
                    b.Navigation("_grafs");
                });
#pragma warning restore 612, 618
        }
    }
}
